name: GroupSystem
version: '${project.version}'
main: de.zillolp.groupsystem.GroupSystem
api-version: '1.20'
commands:
  groupsystem:
    description: "Command for the plugin."
  groups:
    description: "Command for group management."
